name: Actions

on: [push, workflow_dispatch]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      #Rename html title and append link to readme file
      - name: Rename HTML title
        run: .action_scripts/page_title_and_readme_link.sh
        env:
          REPO_NAME: ${{ github.repository }}

      #Commit and Push new readme file.
      - name: Push Readme
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.md'

      #Upload
      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/WebGL/WebGL/

  deploy:
    # Deploy to the github-pages environment
    # (only accepts being run from gh-pages,
    # potentially in a separate workflow file)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v2

